version: "3"

services:
  db:
    container_name: postgres
    image: postgres:13
    restart: on-failure
    volumes:
      - ./database-files:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
